// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8uCub3i3M05Pdwd35v66eCVsnUPiVig',
    appId: '1:885701488523:web:30a17dcb42281a6704098e',
    messagingSenderId: '885701488523',
    projectId: 'zuba-kasir-b27dd',
    authDomain: 'zuba-kasir-b27dd.firebaseapp.com',
    storageBucket: 'zuba-kasir-b27dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWVtmDCCdHzvvnBhKEIubbuLGaCkg_GEg',
    appId: '1:885701488523:android:b566e25db5961d5204098e',
    messagingSenderId: '885701488523',
    projectId: 'zuba-kasir-b27dd',
    storageBucket: 'zuba-kasir-b27dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48BOc6WwwCCFtNELJ-WeNpggnDelHfw0',
    appId: '1:885701488523:ios:912b970b7341c12b04098e',
    messagingSenderId: '885701488523',
    projectId: 'zuba-kasir-b27dd',
    storageBucket: 'zuba-kasir-b27dd.appspot.com',
    iosClientId: '885701488523-09pdq1n7cimcf8po7jbct1kc8npnt6mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.zubaKaris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC48BOc6WwwCCFtNELJ-WeNpggnDelHfw0',
    appId: '1:885701488523:ios:912b970b7341c12b04098e',
    messagingSenderId: '885701488523',
    projectId: 'zuba-kasir-b27dd',
    storageBucket: 'zuba-kasir-b27dd.appspot.com',
    iosClientId: '885701488523-09pdq1n7cimcf8po7jbct1kc8npnt6mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.zubaKaris',
  );
}
